### ISSUE TITLE
from utilsd.config import Registry

### ISSUE THREAD

**Issue by zhang666777** [microsoft/SeqSNN#6]
Cannot find declaration to go to怎么解决

**Comment by Lvchangze** [comment]
Can you provide more detials? I guess this issue may be caused by the conflict conda environment.

**Comment by ZhangZuH23** [comment]
进行训练后显示No checkpoint found in outputs\ispikformer_horizon=24_solar_12_512_2048\checkpoints SeqSNN.runner.base， 
 生成的checkpoint文件为空是什么原因呢

**Comment by Lvchangze** [comment]
> 进行训练后显示No checkpoint found in outputs\ispikformer_horizon=24_solar_12_512_2048\checkpoints SeqSNN.runner.base， 生成的checkpoint文件为空是什么原因呢

Have you tried to create the file folder "outputs"? Or Can you show your whole logs?
Tips:
"No checkpoint found in XXX" is a normal output because when the training starts, there are of course no checkpoints.
If there is a checkpoint on your output folder, our framework will load the checkpoint to the model.

**Comment by ZhangZuH23** [comment]
> > 进行训练后显示No checkpoint found in outputs\ispikformer_horizon=24_solar_12_512_2048\checkpoints SeqSNN.runner.base， 生成的checkpoint文件为空是什么原因呢
> 
> Have you tried creating the folder "outputs"? Or Can you show your whole logs? Hint: "No checkpoint found in XXX" is a normal output, because when the training starts, of course, there is no checkpoint. If you have checkpoints in your output folder, our framework will load the checkpoints into the model. You can wait for a while and see if the training starts.

After "No checkpoint found in outputs\checkpoints" is displayed, the training still does not start or end, and the checkpoints file is always empty，The log files are as follows：
[stdout.log](https://github.com/user-attachments/files/16757545/stdout.log)

**Comment by Lvchangze** [comment]
> > > 进行训练后显示No checkpoint found in outputs\ispikformer_horizon=24_solar_12_512_2048\checkpoints SeqSNN.runner.base， 生成的checkpoint文件为空是什么原因呢
> > 
> > 
> > Have you tried creating the folder "outputs"? Or Can you show your whole logs? Hint: "No checkpoint found in XXX" is a normal output, because when the training starts, of course, there is no checkpoint. If you have checkpoints in your output folder, our framework will load the checkpoints into the model. You can wait for a while and see if the training starts.
> 
> After "No checkpoint found in outputs\checkpoints" is displayed, the training still does not start or end, and the checkpoints file is always empty，The log files are as follows： [stdout.log](https://github.com/user-attachments/files/16757545/stdout.log)

I notice that your path is "WindowsPath<>". I tend to believe your training is starting on CPUs,  whose speed is much slower than that on GPUs. Please use Linux with GPUs to conduct this experiments. Otherwise, the speed will be very very slow.
